-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE public.favorites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  tool_id TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, tool_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "用户可以查看自己的收藏" ON public.favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可以添加收藏" ON public.favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可以删除自己的收藏" ON public.favorites FOR DELETE USING (auth.uid() = user_id);

CREATE TYPE command_category AS ENUM ('mac', 'ollama', 'docker', 'git', 'npm', 'general');

CREATE TABLE public.commands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  category command_category NOT NULL,
  command TEXT NOT NULL,
  description TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.commands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看命令" ON public.commands FOR SELECT USING (true);
CREATE POLICY "认证用户可添加命令" ON public.commands FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE INDEX idx_commands_category ON public.commands(category);

INSERT INTO public.commands (name, category, command, description, tags) VALUES
('安装 Homebrew', 'mac', '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"', 'macOS 包管理器安装', ARRAY['mac', '包管理']),
('安装 Node.js', 'mac', 'brew install node', '通过 Homebrew 安装 Node.js', ARRAY['mac', 'node']),
('安装 pnpm', 'mac', 'brew install pnpm', '安装 pnpm 包管理器', ARRAY['mac', 'pnpm']),
('安装 Git', 'mac', 'brew install git', '安装 Git 版本控制', ARRAY['mac', 'git']),
('安装 Ollama', 'mac', 'brew install ollama', '安装 Ollama 本地 AI 模型', ARRAY['mac', 'ollama']),
('运行 Llama2', 'ollama', 'ollama run llama2', '运行 Llama2 模型', ARRAY['ollama', 'llama']),
('运行 Mistral', 'ollama', 'ollama run mistral', '运行 Mistral 模型', ARRAY['ollama', 'mistral']),
('运行 CodeLlama', 'ollama', 'ollama run codellama', '运行 CodeLlama 编程助手', ARRAY['ollama', 'code']),
('列出本地模型', 'ollama', 'ollama list', '查看已下载的模型', ARRAY['ollama']),
('删除模型', 'ollama', 'ollama rm llama2', '删除指定模型', ARRAY['ollama']),
('Docker 构建', 'docker', 'docker build -t myapp .', '构建 Docker 镜像', ARRAY['docker', 'build']),
('Docker 运行', 'docker', 'docker run -p 3000:3000 myapp', '运行 Docker 容器', ARRAY['docker', 'run']),
('Docker Compose 启动', 'docker', 'docker-compose up -d', '后台启动 Compose 服务', ARRAY['docker', 'compose']),
('查看容器日志', 'docker', 'docker logs -f container_id', '实时查看容器日志', ARRAY['docker', 'logs']),
('Git 初始化', 'git', 'git init', '初始化 Git 仓库', ARRAY['git', 'init']),
('Git 克隆', 'git', 'git clone https://github.com/user/repo.git', '克隆远程仓库', ARRAY['git', 'clone']),
('Git 提交', 'git', 'git add . && git commit -m "message"', '添加并提交更改', ARRAY['git', 'commit']),
('Git 推送', 'git', 'git push origin main', '推送到远程仓库', ARRAY['git', 'push']),
('NPM 安装依赖', 'npm', 'npm install', '安装项目依赖', ARRAY['npm', 'install']),
('NPM 运行开发', 'npm', 'npm run dev', '运行开发服务器', ARRAY['npm', 'dev']),
('PNPM 安装', 'npm', 'pnpm install', '使用 pnpm 安装依赖', ARRAY['pnpm', 'install']);