-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TYPE tool_type AS ENUM ('ai-product', 'website', 'app', 'github', 'skill');

CREATE TABLE public.ai_tools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  type tool_type NOT NULL,
  url TEXT NOT NULL,
  description TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  icon TEXT,
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.ai_tools ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看AI工具" ON public.ai_tools FOR SELECT USING (true);
CREATE POLICY "认证用户可添加AI工具" ON public.ai_tools FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "认证用户可更新自己的AI工具" ON public.ai_tools FOR UPDATE USING (auth.uid() IS NOT NULL);
CREATE POLICY "认证用户可删除自己的AI工具" ON public.ai_tools FOR DELETE USING (auth.uid() IS NOT NULL);

CREATE INDEX idx_ai_tools_type ON public.ai_tools(type);
CREATE INDEX idx_ai_tools_featured ON public.ai_tools(featured);